activation: lrelu
anneal_end: 50
anneal_start: 10
backbone: dtcn
batch_size: 8
best_val_epoch: 115
bidirectional: true
class_names:
- background
- full_flaring
- half_flaring
class_weights:
- 0.06662989304767235
- 0.4933720170808649
- 0.43999808987146277
classifier_type: multiclass
data_config: /home/mattw/Dropbox/research-code/.daart/data_fish_tmp.yaml
data_dir: /home/mattw/Dropbox/shared/segmentation-data/fish
device: cuda
dropout: 0.1
early_stop_history: 4
enable_early_stop: true
expt_dir: /media/mattw/behavior/results/daart/fish/multi-7
expt_ids: &id001
- 1.2.2L
- 1.2.28L
- 1.3.1L
- 1.4.1L
- 2.1.28R
- 3.1.28R
- 3.2.28R
- 1.1.28R
- 1.1.28L
- 1.2.2R
- 1.2.28R
- 1.3.1R
- 1.4.1R
- 2.1.28L
- 3.1.28L
- 3.2.28L
- 6.1.1L
- 6.1.1R
- 6.1.2R
- 6.2.1L
- 6.2.1R
expt_ids_to_keep: *id001
gpus_vis: 0
hpc_exp_number: null
ignore_class: -100
input_size: 18
input_type: features-aug
l2_reg: 0
lambda_pred: 0
lambda_strong: 1
lambda_task: 0
lambda_weak: 0
learning_rate: 0.0001
max_epochs: 1000
min_epochs: 20
model_class: segmenter
model_config: /home/mattw/Dropbox/research-code/.daart/model_tmp.yaml
model_dir: /media/mattw/behavior/results/daart/fish/multi-7/dtcn/
n_hid_layers: 2
n_hid_units: 32
n_lags: 4
output_size: 3
plot_train_curves: true
prob_threshold: 0.9
results_dir: /media/mattw/behavior/results/daart/fish
rng_seed_model: 0
rng_seed_train: 0
save_last_model: false
semi_supervised_algo: null
sequence_length: 1000
sequence_pad: 24
train_config: /home/mattw/Dropbox/research-code/.daart/train_fish_tmp.yaml
train_frac: 1
trial_splits: 9;1;0;0
training_completed: true
tt_experiment_name: ternary3
tt_n_cpu_trials: 1000
tt_n_cpu_workers: 5
tt_version_dir: /media/mattw/behavior/results/daart/fish/multi-7/dtcn/ternary3/version_0
val_check_interval: 5
val_dataset: 0
variational: false
version: 0
